#!/bin/bash

if [[ -z $TOPOSM_ENV_SET ]]; then
    echo "Error: TopOSM environment not set."
    exit 1
fi

SRS900913="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over"
COLORFILE="$HOME/projects/toposm/colors.txt"

# NOTE: X values are negative, since we're west of the 0 meridian
LEFT=$(($XMINLL * -1))
RIGHT=$(($XMAXLL * -1))
BOTTOM=$YMINLL
TOP=$YMAXLL

mkdir -pv $HILLSHADE_DIR
mkdir -pv $COLORMAP_DIR

for x in `seq $RIGHT $LEFT`; do
for y in `seq $BOTTOM $TOP`; do
    BASE=`printf "n%02dw%03d" $y $x`
    FILE=$BASE.tif
    NEDPATH=$NED13_DIR/$FILE

    if [ -f $NEDPATH ] ; then
    echo; echo "***** $NEDPATH"

    # NOTE: Hillshading first then reprojecting seems to yield a better
    # result than vice versa.

    # Render and reproject hillshade
    echo "Rendering hillshade..."
    hillshade $NEDPATH $HILLSHADE_DIR/$BASE.unproj.tif -z 0.00001
    gdalwarp -t_srs "$SRS900913" -r cubicspline -multi -of GTiff \
       $HILLSHADE_DIR/$BASE.unproj.tif $HILLSHADE_DIR/$BASE.tif
    rm $HILLSHADE_DIR/$BASE.unproj.tif

    # Render and reproject colormap
    echo "Rendering colormap..."
    color-relief $NEDPATH $COLORFILE $COLORMAP_DIR/$BASE.unproj.tif
    gdalwarp -t_srs "$SRS900913" -r cubicspline -multi -of GTiff \
       $COLORMAP_DIR/$BASE.unproj.tif $COLORMAP_DIR/$BASE.tif
    rm $COLORMAP_DIR/$BASE.unproj.tif
       
    fi;
done; done

